# Generated by Django 3.2.7 on 2021-11-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('phoneNo', models.CharField(max_length=45)),
                ('age', models.IntegerField(max_length=11)),
                ('address', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'django_project',
                'managed': False,
            },
        ),
    ]
